  on:
    push
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Java JDK
          uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '15'
            check-latest: true
        - name: Build
          run: ./gradlew clean build
