on:
  push
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Java JDK
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
          check-latest: true
      - name: Build
        run: ./gradlew clean build
