  on:
    push
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Java JDK
          uses: actions/setup-java@v2.0.0
        - name: Build
          run: ./gradlew clean build
