  name: pps-ci-lab
  on:
    push:
  jobs:
    Build:
      runs-on: ubuntu-20.04
      steps:
        - name: Install Java
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '15'
        - run: ./gradlew clean build
