name: Lab CI

on:
  push:
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 11
      - name: Build
        run: ./gradlew check
